// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using FileProviderUI;
using FileProvider;
using System.IO;

namespace MyFileProviderUiExtension
{
	public partial class DocumentActionViewController
	{
		public DocumentActionViewController (IntPtr handle) : base (handle)
		{
		}

        [Foundation.Export("prepareForError:")]
        public override void Prepare(NSError error)
        {
            try
            {
                new NSAlert
                {
                    MessageText = "Alert",
                    InformativeText = "Alert prepare with error"
                }.RunModal();

                this.ExtensionContext.CompleteRequest();
            }
            catch (Exception ex)
            {
                error = NSError.FromDomain(new NSString("NSFileProviderErrorDomain"),
               (int)NSFileProviderError.InsufficientQuota, null);

                this.ExtensionContext.CancelRequest(error);
                Console.WriteLine(ex);
            }
        }

        public override void LoadView()
        {
            new NSAlert
            {
                MessageText = "Alert",
                InformativeText = "Alert load view"
            }.RunModal();
        }

        [Foundation.Export("prepareForActionWithIdentifier:itemIdentifiers:")]
        public override void Prepare(string actionIdentifier, NSString[] itemIdentifiers)
        {
            new NSAlert
            {
                MessageText = "Alert",
                InformativeText = "Alert prepare with action identifiers"
            }.RunModal();


            this.ExtensionContext.CompleteRequest();
        }
    }
}
